export interface Scenario {
  id: string;
  title: string;
  preconditions: string;
  userActions: string[];
  checkpoints: string[];
  linkedAc: string;
}

/**
 * Parses the SCENARIOS.md format generated by testPlannerAgent.
 *
 * Example:
 *
 * ### AC1-S1: Successful login
 * - Preconditions:
 *   - User is on the login page
 * - User Actions:
 *   1. Enter username
 *   2. Enter password
 *   3. Click Login
 * - Expected Validation Checkpoints:
 *   1. Inventory page is displayed
 * - Linked Acceptance Criteria: AC1 — "..."
 */

export function parseScenarios(markdown: string): Scenario[] {
  const blocks = markdown.split(/^### /m).slice(1);

  const scenarios: Scenario[] = [];

  for (const block of blocks) {
    const headerMatch = block.match(/^([A-Za-z0-9-]+):\s*(.+)$/m);

    if (!headerMatch) {
      continue;
    }

    const [, id, title] = headerMatch;

    if (!id || !title) {
      continue;
    }

    const preconditions =
      extractBulletSection(block, "Preconditions").join(" ") ||
      "(none stated)";

    const userActions = extractNumberedSection(
      block,
      "User Actions",
    );

    const checkpoints = extractNumberedSection(
      block,
      "Expected Validation Checkpoints",
    );

    const linkedAc =
      block
        .match(
          /-\s*Linked Acceptance Criteria:\s*(.+)$/m,
        )?.[1]
        ?.trim() ?? "(not specified)";

    if (userActions.length === 0 || checkpoints.length === 0) {
      throw new Error(
        `Scenario ${id} is missing User Actions or Expected Validation Checkpoints — ` +
          `check SCENARIOS.md formatting matches testPlannerAgent's expected structure.`,
      );
    }

    // Add the parsed scenario to the array.
    scenarios.push({
      id,
      title: title.trim(),
      preconditions,
      userActions,
      checkpoints,
      linkedAc,
    });
  }

  if (scenarios.length === 0) {
    throw new Error(
      "No scenarios parsed from SCENARIOS.md — run testPlannerAgent first, " +
        "or check its output format.",
    );
  }

  return scenarios;
}

// Extracts a bullet-pointed section from a markdown block, returning the lines as an array of strings.
function extractBulletSection(
  block: string,
  sectionName: string,
): string[] {
  const section = block.match(
    new RegExp(
      `-\\s*${sectionName}:\\s*\\n([\\s\\S]*?)(?=\\n-\\s*[A-Z]|$)`,
    ),
  )?.[1];

  if (!section) {
    return [];
  }

  return section
    .split("\n")
    .map((line) =>
      line.replace(/^\s*-\s*/, "").trim(),
    )
    .filter(Boolean);
}

// Extracts a numbered list section from a markdown block, returning the lines as an array of strings.
function extractNumberedSection(
  block: string,
  sectionName: string,
): string[] {
  const section = block.match(
    new RegExp(
      `-\\s*${sectionName}:\\s*\\n([\\s\\S]*?)(?=\\n-\\s*[A-Z]|$)`,
    ),
  )?.[1];

  if (!section) {
    return [];
  }

  return section
    .split("\n")
    .map((line) =>
      line.replace(/^\s*\d+\.\s*/, "").trim(),
    )
    .filter(Boolean);
}