import { readFileSync, writeFileSync, existsSync, mkdirSync, cpSync, rmSync } from "node:fs";

/**
 * Turns whatever a real `npm test` run just produced into evidence/:
 * - evidence/report.md            human-readable pass/fail summary
 * - evidence/test-results/        raw screenshots/videos/traces (failures)
 * - evidence/playwright-report/   Playwright's static HTML report
 * - evidence/allure-report/       Allure's static HTML report (if built)
 *
 * Run this AFTER `npm test` (or `npm run agent:pipeline && npm test`) —
 * it reads what's already on disk, it doesn't run anything itself.
 */

const RESULTS_JSON = "test-results/results.json";

/// Loads the Playwright test results from the JSON file generated by the Playwright test runner.
function loadResults() {
  if (!existsSync(RESULTS_JSON)) {
    throw new Error(
      `${RESULTS_JSON} not found. Run "npm test" first — playwright.config.ts's ` +
        `json reporter writes this file on every run.`,
    );
  }
  return JSON.parse(readFileSync(RESULTS_JSON, "utf-8"));
}

// Recursively collects test results from the Playwright test suite structure into a flat array of rows for reporting.
function collectTestRows(suite, rows, filePath) {
  for (const spec of suite.specs ?? []) {
    for (const test of spec.tests ?? []) {
      const result = test.results?.[test.results.length - 1];
      rows.push({
        title: `${spec.title}`,
        file: filePath ?? suite.file ?? "",
        status: result?.status ?? test.status ?? "unknown",
        durationMs: result?.duration ?? 0,
        error: result?.error?.message,
      });
    }
  }
  for (const nested of suite.suites ?? []) {
    collectTestRows(nested, rows, filePath ?? suite.file);
  }
}

// Renders the collected test results into a Markdown report, including a summary of passed, failed, and skipped tests, as well as detailed failure information if applicable.
function renderReportMarkdown(results) {
  const rows = [];
  for (const suite of results.suites ?? []) collectTestRows(suite, rows, suite.file);

  const passed = rows.filter((r) => r.status === "passed").length;
  const failed = rows.filter((r) => r.status === "failed" || r.status === "timedOut").length;
  const skipped = rows.filter((r) => r.status === "skipped").length;

  const lines = [
    "# Test Execution Report",
    "",
    `Generated: ${new Date().toISOString()}`,
    "",
    `**Result: ${passed}/${rows.length} passed** (${failed} failed, ${skipped} skipped)`,
    "",
    "| Test | Status | Duration (ms) |",
    "|---|---|---|",
    ...rows.map(
      (r) => `| ${r.title} | ${r.status === "passed" ? "✅ pass" : r.status === "failed" ? "❌ fail" : "⏭ " + r.status} | ${r.durationMs} |`,
    ),
    "",
  ];

  const failures = rows.filter((r) => r.error);
  if (failures.length > 0) {
    lines.push("## Failure details", "");
    for (const f of failures) {
      lines.push(`### ${f.title}`, "", "```", f.error, "```", "");
    }
  }

  lines.push(
    "## Other artifacts in this folder",
    "",
    "- `playwright-report/` — Playwright's interactive HTML report",
    "- `allure-report/` — Allure's HTML report (if generated)",
    "- `test-results/` — raw traces/screenshots/videos for any failures",
    "",
  );

  return lines.join("\n");
}

// Copies a file or directory from src to dest if it exists, removing any existing destination first. Logs the action taken.
function copyIfExists(src, dest) {
  if (!existsSync(src)) {
    console.log(`  (skipping ${src} — not found, nothing to copy)`);
    return;
  }
  rmSync(dest, { recursive: true, force: true });
  cpSync(src, dest, { recursive: true });
  console.log(`  copied ${src} -> ${dest}`);
}

// The main function that orchestrates the evidence building process: creates the evidence directory, generates the Markdown report, and copies relevant artifacts from the test run.
function main() {
  mkdirSync("evidence", { recursive: true });

  const results = loadResults();
  writeFileSync("evidence/report.md", renderReportMarkdown(results));
  console.log("Wrote evidence/report.md");

  copyIfExists("test-results", "evidence/test-results");
  copyIfExists("playwright-report", "evidence/playwright-report");
  copyIfExists("allure-report", "evidence/allure-report");

  console.log("\nevidence/ populated from the most recent run.");
}

main();